# Generated by Django 6.0.6 on 2026-07-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_product_image_alter_customer_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='iva_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA 15%'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal_0',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal tarifa 0%'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal gravado (IVA)'),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='applies_iva',
            field=models.BooleanField(default=True, verbose_name='Aplica IVA'),
        ),
        migrations.AddField(
            model_name='product',
            name='applies_iva',
            field=models.BooleanField(default=True, verbose_name='Aplica IVA'),
        ),
    ]
