# Generated by Django 6.0.6 on 2026-07-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_iva_amount_invoice_subtotal_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento %'),
        ),
    ]
