# Generated by Django 6.0.7 on 2026-07-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADA', 'PAGADA')], default='PENDIENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tipo_pago',
            field=models.CharField(choices=[('CONTADO', 'CONTADO'), ('CREDITO', 'CREDITO')], default='CONTADO', max_length=10),
        ),
    ]
