# Generated by Django 6.0.7 on 2026-07-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_estado_invoice_saldo_invoice_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='clave_acceso',
            field=models.CharField(blank=True, max_length=49),
        ),
        migrations.AddField(
            model_name='invoice',
            name='numero_autorizacion',
            field=models.CharField(blank=True, max_length=49),
        ),
        migrations.AddField(
            model_name='invoice',
            name='xml_generado',
            field=models.BooleanField(default=False),
        ),
    ]
