# Generated by Django 6.0.7 on 2026-07-17 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuotacompra',
            options={'permissions': [('export_cuotacompra', 'Can export cuota compra'), ('print_cuotacompra', 'Can print cuota compra')]},
        ),
    ]
