# Generated by Django 6.0.7 on 2026-07-12 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_estado_invoice_saldo_invoice_tipo_pago'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_orders', to='billing.invoice'),
        ),
    ]
