# Generated by Django 6.0.7 on 2026-07-17 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchase_estado_purchase_saldo_purchase_tipo_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'permissions': [('export_purchase', 'Can export purchase'), ('print_purchase', 'Can print purchase')], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
    ]
