# Generated by Django 6.0.7 on 2026-07-17 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditos_ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuotaventa',
            options={'permissions': [('export_cuotaventa', 'Can export cuota venta'), ('print_cuotaventa', 'Can print cuota venta')]},
        ),
    ]
